# Generated by Django 4.2.1 on 2023-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
