# Generated by Django 4.2.1 on 2023-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_title_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='place',
            name='titles',
        ),
        migrations.AddField(
            model_name='title',
            name='humans',
            field=models.ManyToManyField(related_name='titles', to='titles.human'),
        ),
        migrations.AddField(
            model_name='title',
            name='places',
            field=models.ManyToManyField(related_name='titles', to='titles.place'),
        ),
    ]
